### ISSUE TITLE
Upload Button has no power

### ISSUE THREAD

**Issue by saijayaprakash** [viral-vector/vue-upload-image#11]
I followed all the steps. But when i click upload button nothing pops up. Its better to have a basic example on how to do it.

**Comment by DudeGrim** [comment]
I can confirm that the upload button does not do anything. However, clicking the div surrounding the button opens up the file input dialog, at least for me.

**Comment by viral-vector** [comment]
@saijayaprakash @DudeGrim There is a misconception on how the upload button works. The button is operational on a "can i upload" check; usually after images have been dragged dialog selected. 

*** Images can be set for upload by: 

1. **Drag and dropping them on to the rectangle upload area**.
2. **Selected via dialog by clicking on to the rectangle upload area**.
