### ISSUE TITLE
emit 'upload-image-loaded'   return params

### ISSUE THREAD

**Issue by Luigidefra** [viral-vector/vue-upload-image#12]
why do emit upload-image-loaded return only files.value[key] and not also image.value[key] which is base64?

**Comment by viral-vector** [comment]
> why do emit upload-image-loaded return only files.value[key] and not also image.value[key] which is base64?

I originally developed this extension for my personal uses. Scope of original project did not include events. I introduced the feature as more people utilized this projects. Simply there was no use case.

**Comment by viral-vector** [comment]
You are free to introduce a pull request. If there is greater demand, i will add the feature myself.
