### ISSUE TITLE
How to use the file input

### ISSUE THREAD

**Issue by privateuly** [viral-vector/vue-upload-image#5]
Thanks for this repo.  This component looks nice!  But it seems that I can only upload images by dragging in the photos.  How can I enable to file input so that I can browse and select the photos I want to upload?

**Comment by privateuly** [comment]
Just to clarify, I tried removing the "hidden" attribute from <input type="file"> but when the open file dialog would open up twice before the image loads up on the browser.

**Comment by viral-vector** [comment]
The file input should open when clicking in the open space of the box. It's hidden on purpose & triggered when the container box is clicked.

**Comment by privateuly** [comment]
Got it.  Thanks!
